mlx_lm.lora \
  --model "mlx-community/gemma-3-270m-it-4bit" \
  --train \
  --data ./data \
  --iters 2000 \
  --batch-size 4 \
  --steps-per-report 10 \
  --grad-accumulation-steps 4 \
  --resume-adapter-file ./dsl_adapter/adapters.safetensors \
  --learning-rate 1e-5 \
  --adapter-path ./dsl_adapter
